### PR TITLE
feat: add extension release workflow

### PR DESCRIPTION
**Pull request by tuxity**
Hello,

Here a PR to add the CI/CD for this extension.

I followed official steps from Microsoft documentation https://code.visualstudio.com/api/working-with-extensions/publishing-extension

Tested and working:
- https://github.com/tuxity/vscode-cue/actions/runs/9111230003
- https://marketplace.visualstudio.com/items?itemName=KevinDarcel.cue-syntax

Todos:
- [ ] You need to create a Marketplace Publisher `cuelang.org` here https://marketplace.visualstudio.com/
- [ ] You need to create and setup repository secret `VSCODE_MARKETPLACE_TOKEN` following this documention https://learn.microsoft.com/en-us/azure/devops/organizations/accounts/use-personal-access-tokens-to-authenticate?view=azure-devops&tabs=Windows

Notes:
- I had to rename the extension to `cue-syntax` and display name `CUE Syntax` because the name was already taken by someone else https://github.com/asdine/vscode-cue/blob/main/package.json#L2 (You can appeal to Microsoft if you want to  VSMarketplace@microsoft.com)
- I will remove my app on the marketplace once you guys are ready 👍🏼

### CODE REVIEW

**Comment by tuxity** [comment]
CC @myitcv @mpvl @mvdan

**Comment by myitcv** [comment]
@tuxity - thanks for your patience here. We're just in the process of updating the extension ready for LSP support. 

Please bear with us whilst we get those changes through first.

**Comment by myitcv** [comment]
@tuxity - thank you for your patience here. 

And thank you very much for digging into this so deeply, to the extent that you even published a "test" extension!

As part of the work to make an official VSCode Extension available that supports `cue lsp`, I have a stack of changes that I am currently working on: https://review.gerrithub.io/q/project:cue-lang/vscode-cue+status:open. The changes that you propose here have been variously covered in changes in that stack. Therefore, I would like to suggest we close this PR and pick things up there.

However, noting the work you have contributed in this PR, I have made special mention in this change:

https://review.gerrithub.io/c/cue-lang/vscode-cue/+/1204087


> * I had to rename the extension to `cue-syntax` and display name `CUE Syntax` because the name was already taken by someone else https://github.com/asdine/vscode-cue/blob/main/package.json#L2 (You can appeal to Microsoft if you want to  [VSMarketplace@microsoft.com](mailto:VSMarketplace@microsoft.com))

Thank you for flagging this. We actually know the author of that extension, and are in discussions.

**Comment by tuxity** [comment]
@myitcv Thanks for the feedback, I agree with you let's close this one.
I will unpublished my "test" version once you will release the new version to reduce suggestions in VSCode.

Have a good day!

**Comment by myitcv** [comment]
> Thanks for the feedback, I agree with you let's close this one.

Very gracious of you; thank you for your understanding. And thanks again for the effort you went to to help the stack of changes I linked to. Hopefully, my crediting your work in that stack reflects that thanks.

**Pull request closed without merging**
